import 'reflect-metadata';
import { describe, expect, test } from 'bun:test';
import { inferConfirmation, McpRegistryService } from '../src/McpRegistryService';

const tool = (name: string, annotations?: Record<string, boolean>) =>
  ({ name, description: name, methodKey: 'run', target: class {}, args: [], annotations }) as any;

describe('inferConfirmation', () => {
  test('confirms destructive and destructiveHint tools as danger', () => {
    for (const annotations of [{ destructive: true }, { destructiveHint: true }]) {
      expect(inferConfirmation(tool('theme_appearance_reset', annotations))).toEqual({
        level: 'danger', message: 'mcp.confirm.theme_appearance_reset', autoGenerated: true,
      });
    }
  });

  test('confirms destructive-sounding names as warning', () => {
    expect(inferConfirmation(tool('users_delete_user'))?.level).toBe('warning');
  });

  test('leaves other tools, and an explicit destructive: false, unconfirmed', () => {
    expect(inferConfirmation(tool('theme_presets_list', { readOnlyHint: true }))).toBeNull();
    expect(inferConfirmation(tool('users_delete_user', { destructive: false }))).toBeNull();
    expect(inferConfirmation(tool('theme_x', { destructive: false, destructiveHint: true }))).toBeNull();
  });

  test('registerTool attaches the inferred confirmation', () => {
    const registry = new McpRegistryService();
    registry.registerTool(tool('theme_preset_apply', { destructiveHint: true, idempotentHint: true }));
    expect(registry.tools[0].confirmation?.level).toBe('danger');
  });
});
