import type { NLocationLabels } from "./types";

export type NajmLocationLabelLocale = "en" | "fr" | "ar" | "es";

const ENGLISH_LOCATION_LABELS: NLocationLabels = {
  dialogTitle: "Pick an address",
  dialogDescription: "Search or select a location on the map.",
  openMap: "Select location on map",
  close: "Close",
  cancel: "Cancel",
  confirm: "Confirm address",
  clearPin: "Clear pin",
  searchPlaceholder: "Search by street, city, or postal code",
  search: "Search",
  searching: "Searching…",
  searchEmpty: "No locations found.",
  searchError: "Location search is unavailable.",
  findingAddress: "Finding the address...",
  selected: "Delivery location selected",
  notSelected: "Delivery location not selected",
  changedAfterPin: "Address changed after the pin was selected",
  loading: "Loading map…",
  unavailable: "Map selection is unavailable",
  retry: "Retry",
  currentLocation: "Use current location",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  mapInstructions: "Map. Use arrow keys to move the selected pin. Hold Shift for a larger step.",
  readyAnnouncement: "Map is ready.",
  selectedAnnouncement: "Location selected.",
  addressUpdatedAnnouncement: "Address updated for the selected location.",
  clearedAnnouncement: "Location pin cleared.",
  geolocationUnsupported: "Current location is not supported by this browser.",
  geolocationDenied: "Location permission was denied.",
  geolocationTimeout: "Current location timed out.",
  geolocationUnavailable: "Current location is unavailable.",
  providerError: "The map could not be loaded.",
  resultsAnnouncement: (count) => `${count} location result${count === 1 ? "" : "s"} available.`,
};

export const NAJM_LOCATION_LABELS: Readonly<Record<NajmLocationLabelLocale, NLocationLabels>> =
  Object.freeze({
    en: Object.freeze(ENGLISH_LOCATION_LABELS),
    fr: Object.freeze({
      dialogTitle: "Choisir une adresse",
      dialogDescription: "Recherchez ou selectionnez un emplacement sur la carte.",
      openMap: "Selectionner sur la carte",
      close: "Fermer",
      cancel: "Annuler",
      confirm: "Confirmer l'adresse",
      clearPin: "Effacer le repere",
      searchPlaceholder: "Rechercher par rue, ville ou code postal",
      search: "Rechercher",
      searching: "Recherche en cours...",
      searchEmpty: "Aucun emplacement trouve.",
      searchError: "La recherche d'emplacement est indisponible.",
      findingAddress: "Recherche de l'adresse...",
      selected: "Emplacement de livraison selectionne",
      notSelected: "Emplacement de livraison non selectionne",
      changedAfterPin: "L'adresse a change apres la selection du repere",
      loading: "Chargement de la carte...",
      unavailable: "La selection sur la carte est indisponible",
      retry: "Reessayer",
      currentLocation: "Utiliser la position actuelle",
      zoomIn: "Zoomer",
      zoomOut: "Dezoomer",
      mapInstructions: "Carte. Utilisez les fleches pour deplacer le repere. Maintenez Maj pour un pas plus grand.",
      readyAnnouncement: "La carte est prete.",
      selectedAnnouncement: "Emplacement selectionne.",
      addressUpdatedAnnouncement: "Adresse mise a jour pour l'emplacement selectionne.",
      clearedAnnouncement: "Repere d'emplacement efface.",
      geolocationUnsupported: "La position actuelle n'est pas prise en charge par ce navigateur.",
      geolocationDenied: "L'autorisation de localisation a ete refusee.",
      geolocationTimeout: "La recherche de la position actuelle a expire.",
      geolocationUnavailable: "La position actuelle est indisponible.",
      providerError: "La carte n'a pas pu etre chargee.",
      resultsAnnouncement: (count) => `${count} resultat${count === 1 ? "" : "s"} de localisation disponible${count === 1 ? "" : "s"}.`,
    }),
    ar: Object.freeze({
      dialogTitle: "اختيار عنوان",
      dialogDescription: "ابحث عن موقع أو حدده على الخريطة.",
      openMap: "تحديد الموقع على الخريطة",
      close: "إغلاق",
      cancel: "إلغاء",
      confirm: "تأكيد العنوان",
      clearPin: "مسح العلامة",
      searchPlaceholder: "البحث بالشارع أو المدينة أو الرمز البريدي",
      search: "بحث",
      searching: "جار البحث...",
      searchEmpty: "لم يتم العثور على مواقع.",
      searchError: "البحث عن المواقع غير متاح.",
      findingAddress: "جار العثور على العنوان...",
      selected: "تم تحديد موقع التسليم",
      notSelected: "لم يتم تحديد موقع التسليم",
      changedAfterPin: "تغير العنوان بعد تحديد العلامة",
      loading: "جار تحميل الخريطة...",
      unavailable: "تحديد الموقع على الخريطة غير متاح",
      retry: "إعادة المحاولة",
      currentLocation: "استخدام الموقع الحالي",
      zoomIn: "تكبير",
      zoomOut: "تصغير",
      mapInstructions: "خريطة. استخدم مفاتيح الأسهم لتحريك العلامة المحددة، واضغط Shift لخطوة أكبر.",
      readyAnnouncement: "الخريطة جاهزة.",
      selectedAnnouncement: "تم تحديد الموقع.",
      addressUpdatedAnnouncement: "تم تحديث عنوان الموقع المحدد.",
      clearedAnnouncement: "تم مسح علامة الموقع.",
      geolocationUnsupported: "الموقع الحالي غير مدعوم في هذا المتصفح.",
      geolocationDenied: "تم رفض إذن الموقع.",
      geolocationTimeout: "انتهت مهلة تحديد الموقع الحالي.",
      geolocationUnavailable: "الموقع الحالي غير متاح.",
      providerError: "تعذر تحميل الخريطة.",
      resultsAnnouncement: (count) => `${count} نتائج مواقع متاحة.`,
    }),
    es: Object.freeze({
      dialogTitle: "Elegir una direccion",
      dialogDescription: "Busca o selecciona una ubicacion en el mapa.",
      openMap: "Seleccionar ubicacion en el mapa",
      close: "Cerrar",
      cancel: "Cancelar",
      confirm: "Confirmar direccion",
      clearPin: "Borrar marcador",
      searchPlaceholder: "Buscar por calle, ciudad o codigo postal",
      search: "Buscar",
      searching: "Buscando...",
      searchEmpty: "No se encontraron ubicaciones.",
      searchError: "La busqueda de ubicaciones no esta disponible.",
      findingAddress: "Buscando la direccion...",
      selected: "Ubicacion de entrega seleccionada",
      notSelected: "Ubicacion de entrega no seleccionada",
      changedAfterPin: "La direccion cambio despues de seleccionar el marcador",
      loading: "Cargando mapa...",
      unavailable: "La seleccion en el mapa no esta disponible",
      retry: "Reintentar",
      currentLocation: "Usar ubicacion actual",
      zoomIn: "Acercar",
      zoomOut: "Alejar",
      mapInstructions: "Mapa. Usa las flechas para mover el marcador. Manten Mayus para un paso mayor.",
      readyAnnouncement: "El mapa esta listo.",
      selectedAnnouncement: "Ubicacion seleccionada.",
      addressUpdatedAnnouncement: "Direccion actualizada para la ubicacion seleccionada.",
      clearedAnnouncement: "Marcador de ubicacion borrado.",
      geolocationUnsupported: "Este navegador no admite la ubicacion actual.",
      geolocationDenied: "Se denego el permiso de ubicacion.",
      geolocationTimeout: "Se agoto el tiempo para obtener la ubicacion actual.",
      geolocationUnavailable: "La ubicacion actual no esta disponible.",
      providerError: "No se pudo cargar el mapa.",
      resultsAnnouncement: (count) => `${count} resultado${count === 1 ? "" : "s"} de ubicacion disponible${count === 1 ? "" : "s"}.`,
    }),
  });

export const DEFAULT_LOCATION_LABELS = NAJM_LOCATION_LABELS.en;

/** Resolve a supported base language while accepting regional tags. */
export function getNajmLocationLabels(language: string): NLocationLabels {
  const base = language.trim().toLowerCase().split("-")[0] as NajmLocationLabelLocale;
  return NAJM_LOCATION_LABELS[base] ?? DEFAULT_LOCATION_LABELS;
}
