import type { NLocationLabels } from "./types";

export const DEFAULT_LOCATION_LABELS: NLocationLabels = {
  dialogTitle: "Pick an address",
  dialogDescription: "Search or select a location on the map.",
  openMap: "Select location on map",
  close: "Close",
  cancel: "Cancel",
  confirm: "Confirm address",
  clearPin: "Clear pin",
  searchPlaceholder: "Search by street, city, or postal code",
  search: "Search",
  searching: "Searching…",
  searchEmpty: "No locations found.",
  searchError: "Location search is unavailable.",
  findingAddress: "Finding the address...",
  selected: "Delivery location selected",
  notSelected: "Delivery location not selected",
  changedAfterPin: "Address changed after the pin was selected",
  loading: "Loading map…",
  unavailable: "Map selection is unavailable",
  retry: "Retry",
  currentLocation: "Use current location",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  mapInstructions: "Map. Use arrow keys to move the selected pin. Hold Shift for a larger step.",
  readyAnnouncement: "Map is ready.",
  selectedAnnouncement: "Location selected.",
  addressUpdatedAnnouncement: "Address updated for the selected location.",
  clearedAnnouncement: "Location pin cleared.",
  geolocationUnsupported: "Current location is not supported by this browser.",
  geolocationDenied: "Location permission was denied.",
  geolocationTimeout: "Current location timed out.",
  geolocationUnavailable: "Current location is unavailable.",
  providerError: "The map could not be loaded.",
  resultsAnnouncement: (count) => `${count} location result${count === 1 ? "" : "s"} available.`,
};
