import { Meta, Service } from 'najm-core';
import type { RegisteredTool, McpToolConfirmation } from './types';

const DESTRUCTIVE_NAME_PATTERNS = [
  'delete',
  'remove',
  'destroy',
  'drop',
  'purge',
  'wipe',
  'refund',
  'revoke',
];

@Service()
@Meta({ layer: 'plugin', order: 38 })
export class McpRegistryService {
  public tools: RegisteredTool[] = [];

  registerTool(tool: RegisteredTool): void {
    this.tools.push(this.withAutoConfirmation(tool));
  }

  clear(): void {
    this.tools = [];
  }

  private withAutoConfirmation(tool: RegisteredTool): RegisteredTool {
    if (tool.confirmation) return tool;
    const confirmation = inferConfirmation(tool);
    return confirmation ? { ...tool, confirmation } : tool;
  }
}

export function inferConfirmation(tool: RegisteredTool): McpToolConfirmation | null {
  if (tool.annotations?.destructive === false) return null;

  if (tool.annotations?.destructive === true) {
    return {
      level: 'danger',
      message: `mcp.confirm.${tool.name}`,
      autoGenerated: true,
    };
  }

  const haystack = `${tool.name} ${tool.localName ?? ''}`.toLowerCase();
  if (DESTRUCTIVE_NAME_PATTERNS.some((p) => haystack.includes(p))) {
    return {
      level: 'warning',
      message: `mcp.confirm.${tool.name}`,
      autoGenerated: true,
    };
  }

  return null;
}
