import type { Constructor, InjectionDefinition } from 'najm-core';

export type McpTransport = 'http' | 'sse' | 'stdio';

// ============================================================================
// AUTH TYPES
// ============================================================================

/**
 * Result of MCP auth validation.
 * - `true` — authenticated (no user context)
 * - `false` — rejected
 * - `McpAuthContext` — authenticated with user context (populates ALS)
 */
export type McpAuthResult = boolean | McpAuthContext;

/**
 * User context returned by auth.validate().
 * All keys are set in ALS via container.run(), making them available
 * to @User(), @Owned repos, permission checks, etc.
 */
export interface McpAuthContext {
  /** User object — maps to ALS 'user' key (same as @User() in HTTP) */
  user: any;
  /** User role — maps to ALS 'role' key */
  role?: string;
  /** User permissions — maps to ALS 'permissions' key */
  permissions?: string[];
  /** Additional ALS keys (e.g. owner, info, data, filter) */
  [key: string]: any;
}

// ============================================================================
// CONFIG
// ============================================================================

export interface McpConfig {
  name: string;
  version: string;
  path?: string;
  transports?: McpTransport[];
  cors?: boolean | McpCorsConfig;
  toolTimeout?: number;
  maxBodySize?: number;
  sse?: {
    maxSessions?: number;
    sessionTtl?: number;
  };
  auth?: {
    type: 'bearer' | 'api-key';
    validate: (token: string) => McpAuthResult | Promise<McpAuthResult>;
  };
  oauth?: boolean | {
    issuer?: string;
    token?: string;
  };
}

export interface McpCorsConfig {
  origin?: string | string[];
  credentials?: boolean;
}

export interface ToolMeta {
  name: string;
  description: string;
  methodKey: string | symbol;
  catchErrors?: string;
}

export interface McpValidationSchema {
  parse(data: unknown): unknown;
  strip?: () => McpValidationSchema;
}

export interface McpValidationConfig {
  body?: McpValidationSchema;
  params?: McpValidationSchema;
  query?: McpValidationSchema;
  headers?: McpValidationSchema;
  stripUnknown?: boolean;
  errorStatus?: number;
  errorFormatter?: (error: unknown, target: string) => unknown;
}

export interface McpAnnotations {
  readOnlyHint?: boolean;
  destructive?: boolean;
  idempotent?: boolean;
  openWorldHint?: boolean;
}

export type McpConfirmationLevel = 'notice' | 'warning' | 'danger';

export interface McpToolConfirmation {
  level?: McpConfirmationLevel;
  /**
   * Literal confirmation text or an i18n message key, resolved by consumers
   * using the same language context as normal controller responses.
   */
  message?: string;
  autoGenerated?: boolean;
}

export type McpToolConfirm = boolean | McpToolConfirmation;

export interface RegisteredTool extends ToolMeta {
  target: Constructor;
  group?: string;
  localName?: string;
  validation?: McpValidationConfig;
  validationArgs?: string[];
  validationParamKeys?: string[];
  annotations?: McpAnnotations;
  confirmation?: McpToolConfirmation;
}

export interface McpInjection extends InjectionDefinition {
  type: 'mcp';
  target: Constructor;
  propertyKey: string | symbol;
}
