import type { Constructor, InjectionDefinition } from 'najm-core';

export type McpTransport = 'http' | 'sse' | 'stdio';

// ============================================================================
// AUTH TYPES
// ============================================================================

/**
 * Result of MCP auth validation.
 * - `true` — authenticated (no user context)
 * - `false` — rejected
 * - `McpAuthContext` — authenticated with user context (populates ALS)
 */
export type McpAuthResult = boolean | McpAuthContext;

/**
 * User context returned by auth.validate().
 * All keys are set in ALS via container.run(), making them available
 * to @User(), @Owned repos, permission checks, etc.
 */
export interface McpAuthContext {
  /** User object — maps to ALS 'user' key (same as @User() in HTTP) */
  user: any;
  /** User role — maps to ALS 'role' key */
  role?: string;
  /** User permissions — maps to ALS 'permissions' key */
  permissions?: string[];
  /** Additional ALS keys (e.g. owner, info, data, filter) */
  [key: string]: any;
}

export type McpAuthConfig =
  | {
    type: 'bearer' | 'api-key';
    validate: (token: string) => McpAuthResult | Promise<McpAuthResult>;
  }
  | {
    /** Reuse the installed najm-auth bearer resolver and its revocation checks. */
    type: 'najm-auth';
  };

// ============================================================================
// CONFIG
// ============================================================================

export interface McpConfig {
  name: string;
  version: string;
  path?: string;
  transports?: McpTransport[];
  cors?: boolean | McpCorsConfig;
  /**
   * Include internal target/method names in MCP errors (default: false).
   * Intended only for trusted development environments.
   */
  exposeErrorDetails?: boolean;
  /**
   * Best-effort response timeout per tool invocation, in ms (default 30000;
   * <= 0 disables it). NOTE: this races the controller method — on timeout the
   * client receives UNAVAILABLE but the underlying method keeps running to
   * completion (DB writes, emails, etc. are not cancelled). A client retry can
   * therefore double-execute. Make timeout-sensitive tools idempotent.
   */
  toolTimeout?: number;
  /**
   * Max request body size in bytes for streamable HTTP (default 1 MiB; <= 0
   * disables the check). NOTE: enforced via the Content-Length header only —
   * chunked/streamed requests without a Content-Length bypass it, and the body
   * is buffered in full by the transport. Put a proxy-level limit in front for
   * a hard guarantee.
   */
  maxBodySize?: number;
  /**
   * DNS-rebinding protection for streamable HTTP (MCP spec recommendation for
   * localhost/dev servers). When enabled, the transport validates Host/Origin
   * against the allowlists below. Off by default for backwards compatibility.
   */
  enableDnsRebindingProtection?: boolean;
  /** Allowed Host header values (used when DNS-rebinding protection is on). */
  allowedHosts?: string[];
  /** Allowed Origin header values (used when DNS-rebinding protection is on). */
  allowedOrigins?: string[];
  sse?: {
    maxSessions?: number;
    sessionTtl?: number;
  };
  auth?: McpAuthConfig;
  oauth?: boolean | {
    issuer?: string;
    token?: string;
    /**
     * Opt-in to mount the DEV-ONLY OAuth stub even when NODE_ENV=production.
     * The stub authenticates nobody and issues a static token — never enable
     * this in a real deployment.
     */
    unsafeDevStub?: boolean;
  };
}

export interface McpCorsConfig {
  origin?: string | string[];
  credentials?: boolean;
}

export interface ToolMeta {
  name: string;
  description: string;
  methodKey: string | symbol;
  catchErrors?: string;
}

export interface McpValidationSchema {
  parse(data: unknown): unknown;
  strip?: () => McpValidationSchema;
}

export interface McpValidationConfig {
  body?: McpValidationSchema;
  params?: McpValidationSchema;
  query?: McpValidationSchema;
  headers?: McpValidationSchema;
  stripUnknown?: boolean;
  errorStatus?: number;
  errorFormatter?: (error: unknown, target: string) => unknown;
}

export interface McpAnnotations {
  readOnlyHint?: boolean;
  destructive?: boolean;
  idempotent?: boolean;
  openWorldHint?: boolean;
}

export type McpConfirmationLevel = 'notice' | 'warning' | 'danger';

export interface McpToolConfirmation {
  level?: McpConfirmationLevel;
  /**
   * Literal confirmation text or an i18n message key, resolved by consumers
   * using the same language context as normal controller responses.
   */
  message?: string;
  autoGenerated?: boolean;
}

export type McpToolConfirm = boolean | McpToolConfirmation;

export interface RegisteredTool extends ToolMeta {
  target: Constructor;
  group?: string;
  localName?: string;
  validation?: McpValidationConfig;
  validationArgs?: string[];
  validationParamKeys?: string[];
  validationQueryKeys?: string[];
  annotations?: McpAnnotations;
  confirmation?: McpToolConfirmation;
}

export interface McpInjection extends InjectionDefinition {
  type: 'mcp';
  target: Constructor;
  propertyKey: string | symbol;
}
