import { Injectable, Inject } from 'najm-core';
import { Err, Log, type ILogger } from 'najm-core';
import { I18n, I18nService, type TFn } from 'najm-i18n';
import { EmailService, passwordResetTemplate } from 'najm-email';
import { UserService, type SanitizedUser } from '../users/UserService';
import { UserValidator } from '../users/UserValidator';
import { CookieManager } from './CookieManager';
import { TokenService } from '../tokens/TokenService';
import type { TokenPair, AuthUser, AuthConfig, JwtPayload } from '../types';
import type { CreateUserDto, LoginDto } from '../users/UserDto';
import { AUTH_CONFIG } from '../auth.tokens';
import timestring from 'timestring';
import jwt from 'jsonwebtoken';

@Injectable()
export class AuthService {
  @Inject(AUTH_CONFIG) private config!: AuthConfig;
  @I18n("auth") private t!: TFn;
  @Log() private logger!: ILogger;

  private static readonly DUMMY_HASH = '$2b$10$dummyhashfortimingatackprevention000000000000000';

  constructor(
    private tokenService: TokenService,
    private userService: UserService,
    private userValidator: UserValidator,
    private cookieManager: CookieManager,
    private i18nService: I18nService,
    private emailService: EmailService,
  ) { }

  private isLockoutActive(lockoutUntil?: string | null): boolean {
    if (!lockoutUntil) return false;
    return new Date(lockoutUntil).getTime() > Date.now();
  }

  private nextLockoutUntil(): string {
    const durationMs = timestring(this.config.lockout.duration, 'ms');
    return new Date(Date.now() + durationMs).toISOString();
  }

  /**
   * Decode JWT payload without verification (token was just generated by us).
   * Used to extract accurate roles/permissions for the session cookie cache.
   */
  private decodeAccessToken(accessToken: string): { roles: string[]; permissions: string[] } {
    try {
      const decoded = jwt.decode(accessToken) as JwtPayload | null;
      return {
        roles: decoded?.roles ?? [],
        permissions: decoded?.permissions ?? [],
      };
    } catch {
      return { roles: [], permissions: [] };
    }
  }


  async registerUser(body: CreateUserDto): Promise<SanitizedUser> {
    return await this.userService.create(body);
  }

  async loginUser(body: LoginDto): Promise<TokenPair & { user: SanitizedUser }> {
    const { email, password } = body;
    // Note: @Validate(loginDto) decorator ensures email/password are valid

    const user = await this.userService.findByEmail(email);

    if (user?.lockoutUntil && !this.isLockoutActive(user.lockoutUntil)) {
      await this.userService.resetFailedAttempts(user.id);
      user.failedLoginAttempts = 0;
      user.lockoutUntil = null;
    }

    if (user && this.isLockoutActive(user.lockoutUntil)) {
      Err(this.t('errors.accountLocked'), 423);
    }

    const storedHash = user?.password ?? AuthService.DUMMY_HASH;
    const isValid = await this.userValidator.comparePassword(password, storedHash);

    if (!user || !isValid) {
      if (user) {
        const attempts = await this.userService.incrementFailedAttempts(user.id);
        if (attempts >= this.config.lockout.maxAttempts) {
          await this.userService.setLockout(user.id, this.nextLockoutUntil());
          Err(this.t('errors.accountLocked'), 423);
        }
      }
      Err(this.t('errors.invalidCredentials'));
    }

    if (user.status !== 'active') {
      Err(this.t('errors.accountInactive'));
    }

    if ((user.failedLoginAttempts ?? 0) > 0 || user.lockoutUntil) {
      await this.userService.resetFailedAttempts(user.id);
    }

    const data = await this.tokenService.generateTokens(user.id);
    this.cookieManager.setRefreshToken(data.refreshToken);
    await this.userService.updateLastLogin(user.id);
    const { password: _, failedLoginAttempts: __, lockoutUntil: ___, ...sanitized } = user;

    // Cache session in signed cookie for instant SSR reads.
    // Source roles/permissions from the JWT we just generated (authoritative).
    const { roles, permissions } = this.decodeAccessToken(data.accessToken);
    this.cookieManager.setSessionCookie({
      user: { id: sanitized.id, email: sanitized.email, name: (sanitized as any).name, role: (sanitized as any).role },
      roles,
      permissions,
    });

    return { ...data, user: sanitized };
  }

  async refreshTokens(): Promise<TokenPair> {
    const data = await this.tokenService.refreshTokens();
    this.cookieManager.setRefreshToken(data.refreshToken);

    // Refresh the session cookie so SSR reads stay fresh.
    // Pull roles/permissions from the freshly-issued JWT (authoritative),
    // and user profile from the token-validated DB record.
    const user = await this.tokenService.getUser(`Bearer ${data.accessToken}`);
    if (user) {
      const { roles, permissions } = this.decodeAccessToken(data.accessToken);
      this.cookieManager.setSessionCookie({
        user: { id: user.id, email: user.email, name: (user as any).name, role: (user as any).role },
        roles,
        permissions,
      });
    }

    return data;
  }

  async logoutUser(userId: string, authorization?: string) {
    await this.userValidator.checkUserExists(userId);
    await this.tokenService.logout(userId, authorization);
    this.cookieManager.clearRefreshToken();
    this.cookieManager.clearSessionCookie();

    return { data: null, message: this.t('auth.success.logout') };
  }

  async getUserProfile(userData: AuthUser): Promise<AuthUser & { language: string }> {
    const lang = this.i18nService.getCurrentLanguage();
    return {
      ...userData,
      language: lang,
    };
  }

  async getUserFromCookie(): Promise<SanitizedUser & { language: string }> {
    const userId = await this.tokenService.resolveUserFromCookie();
    const user = await this.userService.getById(userId);
    const lang = this.i18nService.getCurrentLanguage();
    return { ...user, language: lang };
  }

  /**
   * Get current user — prefer access token (no cookie rotation risk),
   * fall back to cookie when no Authorization header is present.
   *
   * Refreshes the session cookie cache only when authoritative roles/permissions
   * are available (from the access token JWT). When called via the refresh-cookie
   * fallback, we cannot reliably populate permissions without a DB round-trip,
   * so we leave the existing cache alone — it will be refreshed by the next
   * login/refresh cycle.
   */
  async getMe(authorization?: string): Promise<SanitizedUser & { language: string }> {
    let result: SanitizedUser & { language: string };
    let cachePayload: { roles: string[]; permissions: string[] } | null = null;

    if (authorization) {
      const user = await this.tokenService.getUser(authorization);
      if (user) {
        const lang = this.i18nService.getCurrentLanguage();
        result = { ...user, language: lang };
        const token = authorization.replace(/^Bearer\s+/i, '');
        cachePayload = this.decodeAccessToken(token);
      } else {
        result = await this.getUserFromCookie();
      }
    } else {
      result = await this.getUserFromCookie();
    }

    // Refresh the session cookie only when we have fresh JWT-derived data
    if (cachePayload) {
      this.cookieManager.setSessionCookie({
        user: { id: result.id, email: result.email, name: (result as any).name, role: (result as any).role },
        roles: cachePayload.roles,
        permissions: cachePayload.permissions,
      });
    }

    return result;
  }

  async forgotPassword(email: string) {
    const user = await this.userService.findByEmail(email);

    if (user) {
      const { token } = await this.tokenService.generateResetToken(user.id);
      const resetLink = `${this.config.frontendUrl}/reset-password?token=${token}`;

      try {
        await this.emailService.sendHtml(
          email,
          this.t('emails.passwordReset.subject'),
          passwordResetTemplate({
            resetLink,
            userName: (user as any).name || email,
          })
        );
      } catch (error) {
        // Log at warn level for operational monitoring
        // Return same message for security (prevent email enumeration)
        this.logger.warn('Password reset email failed', { email, error });
      }
    }

    // Same message regardless - prevents email enumeration
    return { message: this.t('success.passwordResetSent') };
  }

  async changePassword(userId: string, currentPassword: string, newPassword: string) {
    const user = await this.userService.getAuthRecordById(userId);
    if (!user?.password) {
      Err(this.t('errors.invalidCredentials'));
    }

    const isValid = await this.userValidator.comparePassword(currentPassword, user.password);
    if (!isValid) {
      Err(this.t('errors.invalidCredentials'));
    }

    this.userValidator.validatePasswordStrength(newPassword);
    await this.userService.update(userId, { password: newPassword });
    await this.tokenService.invalidateUserAccessTokens(userId);
    await this.tokenService.revokeToken(userId);
    this.cookieManager.clearRefreshToken();
    this.cookieManager.clearSessionCookie();

    return { message: this.t('success.passwordChanged') };
  }

  async resetPassword(token: string, newPassword: string) {
    const userId = await this.tokenService.verifyResetToken(token);
    this.userValidator.validatePasswordStrength(newPassword);
    await this.userService.update(userId, { password: newPassword });
    await this.tokenService.invalidateUserAccessTokens(userId);
    await this.tokenService.revokeToken(userId);
    this.cookieManager.clearRefreshToken();
    this.cookieManager.clearSessionCookie();

    return { message: this.t('success.passwordReset') };
  }
}
