import { defineConfig } from 'tsup';

export default defineConfig({
  tsconfig: 'tsconfig.build.json',
  entry: [
    'src/index.ts',
    'src/auth.ts',
    'src/cache.ts',
    'src/cookies.ts',
    'src/cors.ts',
    'src/database.ts',
    'src/email.ts',
    'src/event.ts',
    'src/guard.ts',
    'src/i18n.ts',
    'src/mcp.ts',
    'src/rate.ts',
    'src/storage.ts',
    'src/validation.ts',
  ],
  format: ['esm'],
  dts: true,
  splitting: false,
  sourcemap: false,
  clean: true,
  outDir: 'dist',
  outExtension: () => ({ js: '.mjs' }),
  bundle: true,
  skipNodeModulesBundle: true,
  external: [
    'najm-core',
    'najm-auth',
    'najm-cache',
    'najm-cookies',
    'najm-cors',
    'najm-database',
    'najm-email',
    'najm-event',
    'najm-guard',
    'najm-i18n',
    'najm-mcp',
    'najm-rate',
    'najm-storage',
    'najm-validation',
    'hono',
    'reflect-metadata',
    'diject',
  ],
  esbuildOptions(options) {
    options.keepNames = true;
  },
});
