import type { StudentPreviewRow } from "./types";

export const smsClasses = [
  { id: "CLS-10", name: "Grade 10" },
  { id: "CLS-11", name: "Grade 11" },
  { id: "CLS-12", name: "Grade 12" },
  { id: "CLS-09", name: "Grade 9" },
  { id: "CLS-08", name: "Grade 8" },
];

export const smsStudents: StudentPreviewRow[] = [
  {
    id: "ST-2041",
    studentCode: "STU2041",
    name: "Sara Idrissi",
    email: "sara.idrissi@sms.test",
    phone: "+212 661 22 10 42",
    class: { name: "Grade 10" },
    section: { name: "A" },
    gender: "F",
    status: "active",
    updatedAt: "2026-06-18",
  },
  {
    id: "ST-1187",
    studentCode: "STU1187",
    name: "Yassine Alami",
    email: "yassine.alami@sms.test",
    phone: "+212 661 14 87 20",
    class: { name: "Grade 11" },
    section: { name: "B" },
    gender: "M",
    status: "active",
    updatedAt: "2026-06-17",
  },
  {
    id: "ST-3022",
    studentCode: "STU3022",
    name: "Nadia Benali",
    email: null,
    phone: "+212 661 45 30 22",
    class: { name: "Grade 12" },
    section: { name: "A" },
    gender: "F",
    status: "graduated",
    updatedAt: "2026-06-15",
  },
  {
    id: "ST-0794",
    studentCode: "STU0794",
    name: "Omar Tazi",
    email: "omar.tazi@sms.test",
    phone: null,
    class: { name: "Grade 10" },
    section: { name: "C" },
    gender: "M",
    status: "active",
    updatedAt: "2026-06-14",
  },
  {
    id: "ST-4419",
    studentCode: "STU4419",
    name: "Mina Bennani",
    email: "mina.bennani@sms.test",
    phone: "+212 661 98 44 19",
    class: { name: "Grade 11" },
    section: { name: "A" },
    gender: "F",
    status: "inactive",
    updatedAt: "2026-06-12",
  },
  {
    id: "ST-2250",
    studentCode: "STU2250",
    name: "Amine Fassi",
    email: "amine.fassi@sms.test",
    phone: "+212 661 71 22 50",
    class: { name: "Grade 12" },
    section: { name: "B" },
    gender: "M",
    status: "active",
    updatedAt: "2026-06-10",
  },
  {
    id: "ST-3184",
    studentCode: "STU3184",
    name: "Leila Haddad",
    email: "leila.haddad@sms.test",
    phone: "+212 661 31 84 09",
    class: { name: "Grade 9" },
    section: { name: "D" },
    gender: "F",
    status: "active",
    updatedAt: "2026-06-09",
  },
  {
    id: "ST-5278",
    studentCode: "STU5278",
    name: "Karim Berrada",
    email: "karim.berrada@sms.test",
    phone: "+212 661 52 78 14",
    class: { name: "Grade 8" },
    section: { name: "E" },
    gender: "M",
    status: "inactive",
    updatedAt: "2026-06-08",
  },
  {
    id: "ST-6640",
    studentCode: "STU6640",
    name: "Hiba Mansouri",
    email: "hiba.mansouri@sms.test",
    phone: "+212 661 66 40 38",
    class: { name: "Grade 10" },
    section: { name: "B" },
    gender: "F",
    status: "active",
    updatedAt: "2026-06-07",
  },
  {
    id: "ST-1906",
    studentCode: "STU1906",
    name: "Adam El Fadili",
    email: null,
    phone: "+212 661 19 06 75",
    class: { name: "Grade 11" },
    section: { name: "C" },
    gender: "M",
    status: "active",
    updatedAt: "2026-06-06",
  },
  {
    id: "ST-7342",
    studentCode: "STU7342",
    name: "Rania Ait Said",
    email: "rania.aitsaid@sms.test",
    phone: "+212 661 73 42 61",
    class: { name: "Grade 12" },
    section: { name: "D" },
    gender: "F",
    status: "graduated",
    updatedAt: "2026-06-05",
  },
  {
    id: "ST-4861",
    studentCode: "STU4861",
    name: "Mehdi Alaoui",
    email: "mehdi.alaoui@sms.test",
    phone: "+212 661 48 61 23",
    class: { name: "Grade 9" },
    section: { name: "A" },
    gender: "M",
    status: "active",
    updatedAt: "2026-06-04",
  },
  {
    id: "ST-9055",
    studentCode: "STU9055",
    name: "Salma Rachidi",
    email: "salma.rachidi@sms.test",
    phone: null,
    class: { name: "Grade 8" },
    section: { name: "C" },
    gender: "F",
    status: "active",
    updatedAt: "2026-06-03",
  },
  {
    id: "ST-6013",
    studentCode: "STU6013",
    name: "Ilyas Cherkaoui",
    email: "ilyas.cherkaoui@sms.test",
    phone: "+212 661 60 13 82",
    class: { name: "Grade 10" },
    section: { name: "E" },
    gender: "M",
    status: "inactive",
    updatedAt: "2026-06-02",
  },
  {
    id: "ST-3772",
    studentCode: "STU3772",
    name: "Aya Zeroual",
    email: "aya.zeroual@sms.test",
    phone: "+212 661 37 72 48",
    class: { name: "Grade 11" },
    section: { name: "D" },
    gender: "F",
    status: "active",
    updatedAt: "2026-06-01",
  },
  {
    id: "ST-8126",
    studentCode: "STU8126",
    name: "Nour Ezzahra",
    email: "nour.ezzahra@sms.test",
    phone: "+212 661 81 26 04",
    class: { name: "Grade 12" },
    section: { name: "E" },
    gender: "F",
    status: "graduated",
    updatedAt: "2026-05-30",
  },
  {
    id: "ST-2448",
    studentCode: "STU2448",
    name: "Anas Lahlou",
    email: "anas.lahlou@sms.test",
    phone: "+212 661 24 48 91",
    class: { name: "Grade 9" },
    section: { name: "B" },
    gender: "M",
    status: "active",
    updatedAt: "2026-05-29",
  },
  {
    id: "ST-6901",
    studentCode: "STU6901",
    name: "Meryem Fikri",
    email: null,
    phone: "+212 661 69 01 16",
    class: { name: "Grade 8" },
    section: { name: "A" },
    gender: "F",
    status: "active",
    updatedAt: "2026-05-28",
  },
];

export const statusMap = {
  active: "success",
  inactive: "warning",
  graduated: "info",
} as const;
